# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Finding Charles
email: charles.tongbm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first site. I learn that to edit this
  section is to go edit in _config.yml. It will appear in my document head meta (for
  Google search results) and in my feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://charles.com" # the base hostname & protocol for your site
twitter_username: tbmtc
github_username: tbmtc
linkedin_username: tbmtc

# Build settings
markdown: kramdown
